service: serverless-demo # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
  - serverless-sam

custom: # stage and logLevel for log function
  stage: ${opt:stage, self:provider.stage} # use stage or get if from the provider.stage. The second paramter is default
  logLevel:
    prod: WARN
    default: DEBUG
  serverless-iam-roles-per-function:
    defaultInherit: true # All function will inherit from the provider's IAM role.

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  environment:
    log_level: ${self:custom.logLevel.${self:custom.stage}, self:custome.logLevel.default} # The variable for the log function
  iamRoleStatements:
    - Effect: Allow
      Action: cloudwatch:PutMetricData
      Resource: '*'
    # profile: voting-profile
  # apiKeys:
  #   - myFirstKey
  #   # - ${opt:stage}-myFirstKey
  #   # - ${env:MY_API_KEY} # you can hide it in a serverless variable
  # usagePlan:
  #   quota:
  #     limit: 5000
  #     offset: 2
  #     period: MONTH
  #   throttle:
  #     burstLimit: 200
  #     rateLimit: 100

# you can add packaging information here
package:
#  include:
#    - ../../node_modules/**
 exclude:
   - DynamodbScripts/**
  #  - exclude-me-dir/**

functions:

  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      restaurants_api: https://bt0pmacdcc.execute-api.us-west-2.amazonaws.com/dev/restaurants
      orders_api: https://bt0pmacdcc.execute-api.us-west-2.amazonaws.com/dev/orders
      cognito_user_pool_id: us-west-2_sYFtW8M2B
      cognito_client_id: 3rl1fppi7b958ahlfj9je9rk6s
      async_metrics: true # Use this variable to control whether send the metrics to CloudWatch Async
    iamRoleStatements:
      - Effect: Allow
        Action: execute-api:Invoke
        Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/restaurants

  # Internal api is protected by an IAM role. The request has be signed when call this api
  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants/
          method: get
          authorizer: aws_iam
          # private: true
    environment:
      restaurants_table: restaurants
      async_metrics: true # Use this variable to control whether send the metrics to CloudWatch Async
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:scan
        Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/restaurants

  # This api is protected by the Cognit user pool. The token has to be included in the request's header when calls.
  search-restaurants:
    handler: functions/search-restaurants.handler
    events:
      - http:
          path: /restaurants/search
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/us-west-2_sYFtW8M2B
    environment:
      restaurants_table: restaurants
      async_metrics: true # Use this variable to control whether send the metrics to CloudWatch Async
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:scan
        Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/restaurants

  
  place-order:
    handler: functions/place-order.handler
    events:
      - http:
          path: /orders
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/us-west-2_sYFtW8M2B
    environment:
      order_events_stream: order-events # The event for Kinesis
      async_metrics: true # Use this variable to control whether send the metrics to CloudWatch Async
    iamRoleStatements:
      - Effect: Allow
        Action: kinesis:PutRecord
        Resource: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events

  # The function is driven by the Kinesis stream
  notify-restaurant:
    handler: functions/notify-restaurant.handler
    events:
      - stream:
          arn: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events
    environment:
      order_events_stream: order-events
      restaurant_notification_topic: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:restaurant-notification
      retry_restaurant_notification_topic: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:retry-restaurant-notification
    iamRoleStatements:
      - Effect: Allow
        Action: kinesis:PutRecord
        Resource: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events
      - Effect: Allow
        Action: sns:Publish
        Resource: 
          - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:restaurant-notification
          - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:retry-restaurant-notification

  # The function handles renotify the restaurant
  retry-notify-restaurant:
    handler: functions/retry-notify-restaurant.handler
    events:
      - sns: retry-restaurant-notification # The Serverless framework will create this sns topic automatically.
    environment:
      order_events_stream: order-events
      restaurant_notification_topic: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:restaurant-notification
    onError: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:restaurant-notification-dlq
    iamRoleStatements:
      - Effect: Allow
        Action: kinesis:PutRecord
        Resource: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events
      - Effect: Allow
        Action: sns:Publish
        Resource: 
          - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:restaurant-notification

  accept-order:
    handler: functions/accept-order.handler
    events:
      - http:
          path: /orders/accept
          method: post
    environment:
      order_events_stream: order-events # The event for Kinesis
      async_metrics: true # Use this variable to control whether send the metrics to CloudWatch Async
    iamRoleStatements:
      - Effect: Allow
        Action: kinesis:PutRecord
        Resource: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events

  notify-user:
    handler: functions/notify-user.handler
    events:
      - stream:
          arn: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events
    environment:
      order_events_stream: order-events
      user_notification_topic: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:user-notification
    iamRoleStatements:
      - Effect: Allow
        Action: kinesis:PutRecord
        Resource: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events
      - Effect: Allow
          Action: sns:Publish
          Resource: 
            - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:user-notification  

  fulfill-order:
    handler: functions/fulfill-order.handler
    events:
      - http:
          path: orders/complete
          method: post
    environment:
      order_events_stream: order-events
      async_metrics: true # Use this variable to control whether send the metrics to CloudWatch Async
    iamRoleStatements:
      - Effect: Allow
        Action: kinesis:PutRecord
        Resource: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events

  # This function will be called every time when we deploy to the apigateway
  auto-create-api-alarms:
    handler: functions/create-alarms.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - aws.apigateway
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - apigateway.amazonaws.com
              eventName:
                - CreateDeployment

resources:
  Resources:
    restaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: restaurants
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    # The resource for the Kinesis stream
    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1

    # SNS topic for restaurant notification
    restaurantNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: restaurant-notification
        TopicName: restaurant-notification

    # SNS topic for user notification
    userNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: user-notification
        TopicName: user-notification

    # SNS topic for the notifcation dead line queue
    restaurantNotificationDLQTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: restaurant-notification-dlq
        TopicName: restaurant-notification-dlq
